DELETE FROM Employee;
DELETE FROM Computer;
DELETE FROM Department;
DELETE FROM TrainingProgram;
DELETE FROM EmployeeTraining;
DELETE FROM ProductType;
DELETE FROM Product;
DELETE FROM Customer;
DELETE FROM PaymentType;
DELETE FROM ItemOrder;
DELETE FROM ProductOrder;

DROP TABLE Employee;
DROP TABLE Computer;
DROP TABLE Department;
DROP TABLE TrainingProgram;
DROP TABLE EmployeeTraining;
DROP TABLE ProductType;
DROP TABLE Product;
DROP TABLE Customer;
DROP TABLE PaymentType;
DROP TABLE ItemOrder;
DROP TABLE ProductOrder;





CREATE TABLE Employee (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	DepartmentId INT NOT NULL,
	IsSuperVisor BOOLEAN NOT NULL,
	FOREIGN KEY(DepartmentId) REFERENCES Department(id)
);

CREATE TABLE Computer (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PurchaseDate DATETIME NOT NULL,
	DecomissionDate DATETIME NOT NULL,
	EmployeeId INT NOT NULL,
	FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
);

CREATE TABLE Department (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Budget 	INT NOT NULL
);

CREATE TABLE TrainingProgram (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	StartDate DATETIME,
	EndDate DATETIME,
	MaxAttendees INTEGER
);

CREATE TABLE EmployeeTraining (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	EmployeeId INTEGER,
	TrainingProgramId INTEGER,
	FOREIGN KEY (EmployeeId) REFERENCES Employee(Id),
	FOREIGN KEY (TrainingProgramId) REFERENCES TrainingProgram(Id)
);

CREATE TABLE ProductType (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL 
);

CREATE TABLE Product (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TypeId INTEGER NOT NULL,
	Price INTEGER NOT NULL,
	Title VARCHAR NOT NULL,
	Description VARCHAR,
	Quantity INTEGER NOT NULL,
	CreatedByCustomerId INTEGER NOT NULL,
	FOREIGN KEY (TypeId) REFERENCES ProductType(Id),
	FOREIGN KEY (CreatedByCustomerId) REFERENCES Customer(Id)
);

CREATE TABLE Customer (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL, 
	LastName TEXT NOT NULL,
	AcctCreatedOn DATETIME ,
	LastActive DATETIME
);

CREATE TABLE PaymentType (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	AcctNumber INT NOT NULL,
	Name TEXT NOT NULL,
	CustomerId INT NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id)
);

CREATE TABLE ItemOrder (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CustomerId INT NOT NULL,
	PaymentType INT,
	Completed BOOLEAN NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id) 
);

CREATE TABLE ProductOrder (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ItemOrderId INT NOT NULL,
	ProductId INT NOT NULL,
	FOREIGN KEY (ItemOrderId) REFERENCES ItemOrder(Id),
	FOREIGN KEY (ProductId) REFERENCES Product(Id)
);

